defaults: &DEFAULTS
  main_app_url: http://localhost:3000/
  main_app_api_url: http://localhost:3000/
  login_url: http://localhost:3000/users/sign_in
  logout_url: http://localhost:3000/users/sign_out
  signup_url: http://localhost:3000/users/sign_up
  api_auth_token: 'M9812Y125T-V234BCOV6-B7PGL23WM-S68CAS53FNGO2B-4JGNT-6RU'
  store_url: http://localhost:5000/
  forum_url: http://localhost:4000/

development:
  <<: *DEFAULTS

test:
  <<: *DEFAULTS

production:
  <<: *DEFAULTS
  main_app_url: http://dev.pointgaming.com/
  main_app_api_url: https://dev.pointgaming.com/
  login_url: https://dev.pointgaming.com/users/sign_in
  logout_url: https://dev.pointgaming.com/users/sign_out
  signup_url: https://dev.pointgaming.com/users/sign_up
  api_auth_token: '25ds-45p56q63-56b75s5m-ndma2fd86gkjo4n6-5124z5568-68f9s'
  store_url: http://store.pointgaming.com/
  forum_url: http://forums.pointgaming.com/
